<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>poinTab</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.view.View</value>
      <webElementGuid>66c5af8c-3f6a-40d6-a5e0-ea254f85f963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7a382d2e-1cc6-4013-ba9a-62b2c394e069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.example.sustain_tour_mobile</value>
      <webElementGuid>5ab77cc6-0646-4d8e-995e-1c473574c3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-desc</name>
      <type>Main</type>
      <value>Tentang Desti Point
Perolehan Poin
Dapatkan 1 Desti Poin untuk setiap transaksi sebesar Rp10.000 dan berlaku kelipatannya.
Contoh: Transaksi sebesar Rp45.000 akan mendapatkan 4 Desti Poin ; transaksi sebesar Rp21.000 akan mendapatkan 2 Desti Poin
Pemakaian Poin
Dapatkan potongan harga sebesar Rp1.000 untuk setiap 10 poin yang digunakan. Potongan harga ini berlaku secara kelipatan.
Contoh: Poin sebanyak 35 dapat digunakan untuk potongan harga senilai Rp3.000 ; poin sebanyak 51 dapat digunakan untuk potongan harga senilai Rp5.000</value>
      <webElementGuid>399555dd-4b27-44f4-9432-71f524aa3ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac8d9ff3-293a-44cb-b035-ea49b27a5ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4664e3de-9333-40a0-ba11-6b41ca3fc912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34a7d7b4-9795-4a96-b503-293e5087555c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>556559af-7ea0-4510-8798-5d134ada9270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66b2cf87-03e7-429e-bfb5-b6612d8de654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>031caa1e-1759-4b7e-8d65-1300b1b9cb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46efa2f1-ffad-4959-9bdd-ff2a578f3f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>867fda73-9b02-461d-a108-5e2ce7e096a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d4cbe7d-9bd3-440a-81e2-4f2faa13cd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5df007b-91eb-46a6-98ed-795d10233420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>64658b15-8abe-4e54-a696-e0ef404284dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>942</value>
      <webElementGuid>acb95a36-60a2-4acb-a4ad-8a6d44f3cae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1080</value>
      <webElementGuid>09e6b5ce-1c8e-4a4a-a2dd-938270a81a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1212</value>
      <webElementGuid>77478609-2b03-4fa0-92d7-88f7b7fe5de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[0,942][1080,2154]</value>
      <webElementGuid>a828605f-24f0-4c19-8f74-3bd23f79d869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fda4ed54-78b1-4823-a094-7d47df871094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>54e47e72-f575-480d-af98-2a704d7a5348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0c81c6df-3dcb-47e4-b342-8de597f28a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]</value>
      <webElementGuid>911f6f97-dfea-4d7e-aa2b-712ce340c247</webElementGuid>
   </webElementProperties>
   <locator>Tentang Desti Point
Perolehan Poin
Dapatkan 1 Desti Poin untuk setiap transaksi sebesar Rp10.000 dan berlaku kelipatannya.
Contoh: Transaksi sebesar Rp45.000 akan mendapatkan 4 Desti Poin ; transaksi sebesar Rp21.000 akan mendapatkan 2 Desti Poin
Pemakaian Poin
Dapatkan potongan harga sebesar Rp1.000 untuk setiap 10 poin yang digunakan. Potongan harga ini berlaku secara kelipatan.
Contoh: Poin sebanyak 35 dapat digunakan untuk potongan harga senilai Rp3.000 ; poin sebanyak 51 dapat digunakan untuk potongan harga senilai Rp5.000</locator>
   <locatorStrategy>ACCESSIBILITY</locatorStrategy>
</MobileElementEntity>
